### ISSUE TITLE
Variant with Blake3 instead of Keccak

### ISSUE THREAD

**Issue by funny-falcon** [jedisct1/rust-sthash#11]
Blake3 could work both in MAC and XOF mode, therefore could be used instead of Keccak.

I understand, it will be other algorithm, but did you consider to create such version?

**Comment by jedisct1** [comment]
Hi,

That would totally work!

However, cSHAKE and KMAC are only used for optional key expansion and for finalization. 

Given the typical use case of stHash, replacing these with something else is not going to make any significant speed difference. This can be revisited once optimized BLAKE3 implementations are widely available outside Rust. Meanwhile, it doesn't hurt to stay conservative.
